name: Pendulum Coffee
favicon: null
layout_spectrum: 0.98668
typography_spectrum: 0.76332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ed6741'
    - '#ee237c'
    - '#15a1b2'
    - '#f7bcab'
  brandStrength: 0.4495527227409184
  lightness: 0.26277913083322346
  saturation: 0.8957457032520324
  rhythmicContrast: 0.2048810354899615
purpose: []
